using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WildShapeSwitchStatement
{
    public static class MonsterList
    {
        public static readonly string[] Monsters =
        {
            "Baboon",
            "Badger",
            "Bat",
            "Cat",
            "Crab",
            "Deer",
            "Eagle",
            "Frog",
            "Giant Fire Beetle",
            "Goat",
            "Hawk",
            "Hyena",
            "Jackal",
            "Lizard",
            "Octopus",
            "Owl",
            "Quipper",
            "Rat",
            "Raven",
            "Scorpion",
            "Sea Horse",
            "Spider",
            "Vulture",
            "Weasel",
            "Blood Hawk",
            "Camel",
            "Flying Snake",
            "Giant Crab",
            "Giant Rat",
            "Giant Weasel",
            "Mastiff",
            "Mule",
            "Poisonous Snake",
            "Pony",
            "Stirge",
            "Axe Beak",
            "Boar",
            "Constrictor Snake",
            "Draft Horse",
            "Elk",
            "Giant Badger",
            "Giant Bat",
            "Giant Centipede",
            "Giant Frog",
            "Giant Lizard",
            "Giant Owl",
            "Giant Poisonous Snake",
            "Giant Wolf Spider",
            "Panther",
            "Pteranodon",
            "Riding Horse",
            "Wolf",
            "Ape",
            "Black Bear",
            "Crocodile",
            "Giant Goat",
            "Giant Sea Horse",
            "Giant Wasp",
            "Reef Shark",
            "Warhorse",
            "Brown Bear",
            "Dire Wolf",
            "Giant Eagle",
            "Giant Hyena",
            "Giant Octopus",
            "Giant Spider",
            "Giant Toad",
            "Giant Vulture",
            "Lion",
            "Tiger",
            "Allosaurus",
            "Giant Boar",
            "Giant Constrictor Snake",
            "Giant Elk",
            "Hunter Shark",
            "Plesiosaurus",
            "Polar Bear",
            "Rhinoceros",
            "Saber-Toothed Tiger",
            "Ankylosaurus",
            "Giant Scorpion",
            "Killer Whale",
            "Elephant",
            "Giant Crocodile",
            "Giant Shark",
            "Triceratops",
            "Mammoth",
            "Giant Ape",
            "Tyrannosaurus Rex",
            "Air Elemental",
            "Earth Elemental",
            "Fire Elemental",
            "Water Elemental"
        };
    }
}
